import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ==========================================
# PHASE 1: DATA ACQUISITION
# ==========================================
print("--- Fetching Real-World Financial Data ---")
ticker = "AAPL"
# Fetch 5 years of daily data
stock_data = yf.download(ticker, start="2019-01-01", end="2024-01-01")

# Flatten multi-index columns if present (common in newer yfinance versions)
if isinstance(stock_data.columns, pd.MultiIndex):
    stock_data.columns = stock_data.columns.get_level_values(0)

print(f"Successfully downloaded {len(stock_data)} trading days for {ticker}.")

# ==========================================
# PHASE 2: FEATURE ENGINEERING
# ==========================================
print("--- Engineering Financial Indicators ---")
df = stock_data.copy()

# 1. Daily Returns: Percentage change between today's and yesterday's close
df['Daily_Return'] = df['Close'].pct_change()

# 2. Moving Averages: Smooth out price data to identify trends
df['SMA_20'] = df['Close'].rolling(window=20).mean() # 20-day trend
df['SMA_50'] = df['Close'].rolling(window=50).mean() # 50-day trend

# 3. Volatility: Rolling standard deviation of returns
df['Volatility_20'] = df['Daily_Return'].rolling(window=20).std()

# 4. Target Variable: 1 if tomorrow's price is higher than today's, else 0
# We use shift(-1) to look at the next day's closing price
df['Target'] = np.where(df['Close'].shift(-1) > df['Close'], 1, 0)

# Drop NaN values generated by the rolling windows and shifting
df.dropna(inplace=True)
print(f"Dataset shape after engineering and cleaning: {df.shape}")

# ==========================================
# PHASE 3: EXPLORATORY DATA ANALYSIS (EDA)
# ==========================================
print("--- Generating Visualizations ---")
sns.set_theme(style="darkgrid")
fig, axes = plt.subplots(2, 1, figsize=(14, 12))

# Plot 1: Price and Moving Averages
axes[0].plot(df.index, df['Close'], label='Closing Price', color='black', alpha=0.6, linewidth=1)
axes[0].plot(df.index, df['SMA_20'], label='20-Day SMA', color='blue', linewidth=1.5)
axes[0].plot(df.index, df['SMA_50'], label='50-Day SMA', color='red', linewidth=1.5)
axes[0].set_title(f'{ticker} Stock Price and Moving Averages', fontsize=14, fontweight='bold')
axes[0].set_ylabel('Price (USD)')
axes[0].legend()

# Plot 2: Correlation Heatmap of Features
# We check how our engineered features correlate with each other
features_to_correlate = ['Close', 'Daily_Return', 'SMA_20', 'SMA_50', 'Volatility_20', 'Target']
corr_matrix = df[features_to_correlate].corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f', ax=axes[1], vmin=-1, vmax=1)
axes[1].set_title('Feature Correlation Heatmap', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.show()

# ==========================================
# PHASE 4: PREDICTIVE MODELING (MACHINE LEARNING)
# ==========================================
print("\n--- Training Predictive Model ---")

# Define features (X) and target (y)
features = ['Daily_Return', 'SMA_20', 'SMA_50', 'Volatility_20']
X = df[features]
y = df['Target']

# Time-Series Split: NEVER use random train_test_split on financial data!
# We must train on the past and test on the future to prevent data leakage.
split_index = int(len(df) * 0.8) # 80% train, 20% test
X_train, X_test = X.iloc[:split_index], X.iloc[split_index:]
y_train, y_test = y.iloc[:split_index], y.iloc[split_index:]

print(f"Training on {len(X_train)} days, Testing on {len(X_test)} days.")

# Initialize and train the Random Forest model
# We limit depth and estimators to prevent overfitting on noisy stock data
model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
model.fit(X_train, y_train)

# ==========================================
# PHASE 5: EVALUATION & CONCLUSIONS
# ==========================================
print("\n--- Model Evaluation ---")
y_pred = model.predict(X_test)

# 1. Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Directional Accuracy: {accuracy * 100:.2f}%\n")

# 2. Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=['Down (0)', 'Up (1)']))

# 3. Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens', 
            xticklabels=['Predicted Down', 'Predicted Up'], 
            yticklabels=['Actual Down', 'Actual Up'])
plt.title('Prediction Confusion Matrix')
plt.show()

# Final Conclusion Printout
print("\n--- Key Project Conclusions ---")
print("1. Financial data is highly noisy. Predicting exact prices is nearly impossible, but predicting directional movement (Up/Down) provides a measurable baseline.")
print("2. The correlation heatmap reveals that Moving Averages are highly correlated with price, but Daily Returns and Volatility are independent, making them better ML features.")
print(f"3. The Random Forest model achieved an accuracy of {accuracy * 100:.2f}%. In real-world trading, an accuracy consistently above 52-53% is often considered enough to generate a statistical edge.")